[workspace]
resolver = "2"
members = ["crates/guardian", "crates/panel", "crates/playit-integration"]
exclude = ["vendor"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/nglmercer/minecraft-server-rs"

[workspace.dependencies]
java-path = { path = "vendor/java-path-rs", features = ["install", "serde"] }
minecraft-core = { path = "vendor/minecraft-core-rs" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
anyhow = "1"
tracing = "0.1"
async-trait = "0.1"
playit-ipc = {
    git = "https://github.com/nglmercer/playit-agent",
    rev = "5fa9a31ff042ac0fb12bfcb9bb4f54a3bcbd62cd"
}

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
